/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.EnterpriseResourcePlanning.view;

/**
 *
 * @author david
 */
public class FrmEnterpriseResourcePlanning extends javax.swing.JFrame {

    /**
     * Creates new form FrmEnterpriseResourcePlanning
     */
    public FrmEnterpriseResourcePlanning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInterpriseResourcePlanning = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();
        itmHelp = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnuHumanResources = new javax.swing.JMenu();
        itmEmployeeRecords = new javax.swing.JMenuItem();
        mnuDepartamentFinance = new javax.swing.JMenu();
        itmPaymentRoll = new javax.swing.JMenuItem();
        itmSalaryRecords = new javax.swing.JMenuItem();
        itmMonetaryincome = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo-PC\\Desktop\\kleber chavez\\univercidad\\fundamentos de la ingeieria\\java\\ima.jpeg")); // NOI18N

        mnuInterpriseResourcePlanning.setText("Interprise Resource Planning");

        itmAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAbout.setText("About");
        itmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAboutActionPerformed(evt);
            }
        });
        mnuInterpriseResourcePlanning.add(itmAbout);

        itmHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmHelp.setText("Help");
        itmHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmHelpActionPerformed(evt);
            }
        });
        mnuInterpriseResourcePlanning.add(itmHelp);

        itmExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuInterpriseResourcePlanning.add(itmExit);

        jMenuBar1.add(mnuInterpriseResourcePlanning);

        mnuHumanResources.setText("Human Resources");

        itmEmployeeRecords.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmEmployeeRecords.setText("Employee Records");
        itmEmployeeRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEmployeeRecordsActionPerformed(evt);
            }
        });
        mnuHumanResources.add(itmEmployeeRecords);

        jMenuBar1.add(mnuHumanResources);

        mnuDepartamentFinance.setText("Departament Finance");

        itmPaymentRoll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmPaymentRoll.setText("Payment Roll");
        itmPaymentRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPaymentRollActionPerformed(evt);
            }
        });
        mnuDepartamentFinance.add(itmPaymentRoll);

        itmSalaryRecords.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSalaryRecords.setText("Salary Records");
        itmSalaryRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSalaryRecordsActionPerformed(evt);
            }
        });
        mnuDepartamentFinance.add(itmSalaryRecords);

        itmMonetaryincome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmMonetaryincome.setText("Monetary income");
        itmMonetaryincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMonetaryincomeActionPerformed(evt);
            }
        });
        mnuDepartamentFinance.add(itmMonetaryincome);

        jMenuBar1.add(mnuDepartamentFinance);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmPaymentRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPaymentRollActionPerformed
     FrmPaymentRoll frmPaymentRoll = new FrmPaymentRoll ();
  this.setVisible(false);
 frmPaymentRoll.setVisible(true);
    }//GEN-LAST:event_itmPaymentRollActionPerformed

    private void itmEmployeeRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEmployeeRecordsActionPerformed
     FrmEmployeRecords frmEmployeRecords = new FrmEmployeRecords ();
  this.setVisible(false);
 frmEmployeRecords.setVisible(true);
    }//GEN-LAST:event_itmEmployeeRecordsActionPerformed

    private void itmSalaryRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSalaryRecordsActionPerformed
FrmSalaryRecords frmSalaryRecords = new FrmSalaryRecords ();
  this.setVisible(false);
 frmSalaryRecords.setVisible(true);
    }//GEN-LAST:event_itmSalaryRecordsActionPerformed

    private void itmMonetaryincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMonetaryincomeActionPerformed
     FrmMonetaryincome frmMonetaryincome = new FrmMonetaryincome();
  this.setVisible(false);
 frmMonetaryincome.setVisible(true);
    }//GEN-LAST:event_itmMonetaryincomeActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
       this.dispose();
    }//GEN-LAST:event_itmExitActionPerformed

    private void itmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAboutActionPerformed
     FrmAbout frmAbout = new FrmAbout ();
  this.setVisible(false);
 frmAbout.setVisible(true);
    }//GEN-LAST:event_itmAboutActionPerformed

    private void itmHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmHelpActionPerformed
    FrmHelp frmHelp = new FrmHelp ();
  this.setVisible(false);
 frmHelp.setVisible(true);
    }//GEN-LAST:event_itmHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEnterpriseResourcePlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEnterpriseResourcePlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEnterpriseResourcePlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEnterpriseResourcePlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEnterpriseResourcePlanning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmEmployeeRecords;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmHelp;
    private javax.swing.JMenuItem itmMonetaryincome;
    private javax.swing.JMenuItem itmPaymentRoll;
    private javax.swing.JMenuItem itmSalaryRecords;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuDepartamentFinance;
    private javax.swing.JMenu mnuHumanResources;
    private javax.swing.JMenu mnuInterpriseResourcePlanning;
    // End of variables declaration//GEN-END:variables
}
